import { StyleSheet } from "react-native";
import { color } from "@/colors";

export const styles = StyleSheet.create({
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    zIndex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
  },
  loadingIndicator: {
    transform: [{ scale: 1.5 }],
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    padding: 20,
  },
  modalContainer: {
    backgroundColor: color.secondaryColor,
    borderRadius: 20,
    maxHeight: "85%",
    shadowColor: color.primaryColor,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: color.borderColor,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: color.textColor,
    letterSpacing: 0.5,
  },
  closeButton: {
    padding: 4,
    borderRadius: 20,
    backgroundColor: color.tertiaryColor + "20",
  },
  scrollContainer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  section: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: color.primaryColor,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  inputCard: {
    backgroundColor: color.inputBgColor,
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: color.inputBorderColor,
    shadowColor: color.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    position: "relative",
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "500",
    color: color.tertiaryColor,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  inputField: {
    fontSize: 15,
    color: color.textColor,
    fontWeight: "500",
    paddingVertical: 8,
    paddingRight: 30,
  },
  bioInput: {
    height: 80,
    textAlignVertical: "top",
    lineHeight: 20,
  },
  inputIcon: {
    position: "absolute",
    right: 16,
    top: 42,
  },
  pickerCard: {
    paddingVertical: 8,
  },
  picker: {
    color: color.textColor,
  },
  placeholderItem: {
    color: color.tertiaryColor,
  },
  pickerItem: {
    fontSize: 14,
    color: color.textColor,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: color.borderColor,
    marginTop: 10,
  },
  primaryButton: {
    backgroundColor: color.primaryColor,
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 10,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    shadowColor: color.primaryColor,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  primaryButtonText: {
    color: color.secondaryColor,
    fontWeight: "600",
    fontSize: 14,
    letterSpacing: 0.3,
  },
  disabledPrimaryButton: {
    backgroundColor: color.solidColor,
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 10,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    shadowColor: color.solidColor,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: color.borderColor,
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: color.secondaryColor,
  },
  secondaryButtonText: {
    color: color.tertiaryColor,
    fontWeight: "600",
    fontSize: 14,
    letterSpacing: 0.3,
  },
});
