import { StyleSheet } from "react-native";
import { color } from "@/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-end",
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  content: {
    backgroundColor: "white",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    shadowColor: color.black,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 20,
    maxHeight: "85%",
    minHeight: "30%",
    width: "100%",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: color.primaryColor + "40",
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: color.primaryColor,
    letterSpacing: 0.5,
  },
  detailsContainer: {
    marginTop: 16,
    gap: 12,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: color.borderLight,
  },
  label: {
    fontSize: 16,
    color: "#666",
    fontWeight: "500",
    flex: 1,
  },
  value: {
    fontSize: 16,
    fontWeight: "600",
    flex: 2,
    textAlign: "right",
  },
  contentContainer: {
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: color.borderLight,
    marginBottom: 8,
  },
  contentText: {
    fontSize: 16,
    color: "#444",
    lineHeight: 24,
    backgroundColor: "#f8f8f8",
    padding: 12,
    borderRadius: 8,
  },
  fileContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: "#f8f8f8",
    padding: 12,
    borderRadius: 8,
  },
  fileIconContainer: {
    backgroundColor: color.primaryColor + "20",
    padding: 10,
    borderRadius: 12,
    shadowColor: color.primaryColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  fileDetails: {
    flex: 1,
  },
  fileName: {
    fontSize: 16,
    color: "#333",
    fontWeight: "600",
  },
  fileSize: {
    fontSize: 13,
    color: color.emptyText,
    marginTop: 4,
    fontWeight: "500",
  },
  replySection: {
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#f8f8f8",
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: color.primaryColor,
  },
  sectionLabel: {
    fontSize: 13,
    color: color.primaryColor,
    fontWeight: "600",
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-end",
  },
});
