import { StyleSheet } from "react-native";
import { color } from "@/colors";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: color.background,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  attachmentButton: {
    padding: 10,
    borderRadius: 20,
    backgroundColor: color.white,
    elevation: 3,
    shadowColor: color.iconDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  inputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: color.white,
    borderRadius: 30,
    paddingHorizontal: 16,
    minHeight: 48,
    maxHeight: 120,
    elevation: 2,
    shadowColor: color.iconDark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    color: color.textPrimary,
    paddingVertical: 10,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: color.primaryColor,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: color.primaryDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  recordingContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: color.recordingBg,
    borderRadius: 30,
    padding: 16,
  },
  recordingIndicator: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: color.danger,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  recordingTimer: {
    fontSize: 16,
    fontWeight: "600",
    color: color.danger,
  },
  cancelRecordingButton: {
    marginLeft: "auto",
    padding: 8,
    borderRadius: 16,
    marginRight: 12,
    backgroundColor: color.white,
  },
  replyPreviewContainer: {
    backgroundColor: color.replyBackground,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: color.primary,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  replyContent: {
    flex: 1,
  },
  replySender: {
    fontSize: 14,
    fontWeight: "600",
    color: color.primary,
    marginBottom: 4,
  },
  replyText: {
    fontSize: 14,
    color: color.textSecondary,
    lineHeight: 18,
  },
  closeButton: {
    padding: 4,
    borderRadius: 12,
    backgroundColor: color.white,
  },
  blockedContainer: {
    backgroundColor: color.background,
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 1,
    borderTopColor: color.border,
  },
  blockedText: {
    fontSize: 14,
    color: color.textSecondary,
    textAlign: "center",
    lineHeight: 20,
  },
  gradientButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  mediaTypeIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: color.primary + "20",
    justifyContent: "center",
    alignItems: "center",
  },
  replyMessageType: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  urlText: {
    color: "blue",
    textDecorationLine: "underline",
  },
});
